// monsters.js - Monster Library
//NOTE: Stress: and GM Token: are keywords.
const defaultMonsters = [

    // You can easily add more monsters here:
        {
        name: "Ankheg",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: - Armor can reduce Hits by points equal to Modifier. 1 Stress: Breath Acid - Roll damage dice equal to the monster Tier and reduce the targets Threshold by +2 per Tier.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Animated Armor",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 1 Stress: - Armor can reduce Hits by points equal to Modifier.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Awakened Shrub",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 1 Stress: Grapple - Select a target and force them to roll a STR/DEX Save to resist. On a fail the target gains the Grappled condition.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Azer",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Illumination - Shed bright light 30ft. 1 Stress: Aura Burning  - Any enemy creature in 10ft Range at the start of their turn also takes +5 per monster Tier damage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Balor",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
            {
        name: "Banshee",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Barbed Devil",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Barlgura",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
            {
        name: "Basilisk",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Behir",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Beholder",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Black Pudding",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Blink Dog",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Teleport to any where within sight and 60ft range.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Bone Devil",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Bugbear",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Bullywug",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Pounce - Can jump onto the a target requiring a STR Save or be knocked prone. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Cambion",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Carrion Crawler",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Centaur",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Chain Devil",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
                {
        name: "Chimera",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },    
            {
        name: "Chuul",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },      
        {
        name: "Cloaker",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Cockatrice",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "3 Stress: Petrifying Gaze - Force any creature looking at the creature to roll a CON Save or at the end of their next round turn to Stone.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Couatl",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Crawling Claw",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "3 Stress: Life Drain - Remove 1HP from the target's total HP. (<i>Until after a Long Rest.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Cyclops",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Death Dog",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Demi-Lich",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Death Knight",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Dire Wolf",
        tier: 2,
        hp: 4,
        stress: 3,
        evasion: 13,
        thresholdLow: 11,
        thresholdHigh: 20,
        damageDice: "1d6",
        attackMod: 5,
        features: "1 Stress: Fear - Force a WIS Save a creature that fails takes a Stress. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                        image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Displacer Beast",
        tier: 1,
        hp: 4,
        stress: 3,
        evasion: 12,
        thresholdLow: 11,
        thresholdHigh: 20,
        damageDice: "1d6",
        attackMod: 5,
        features: "2 Stress: Displacement - The target's Evasion increases by +2 and all Attack rolls against it are made with Disadvantage. Pseudopod - Make a ranged attack out to 10ft. ",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Djinni",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Doppleganger",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Dragon (Ancient)",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Dragon (Black)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Blue)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (Bronze)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Copper)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (Green)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Gold)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (Red)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Silver)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Dragon Turtle",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (White)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Dragon (Young)",
        tier: 5,
        hp: 20,
        stress: 10,
        evasion: 17,
        thresholdLow: 29,
        thresholdHigh: 44,
        damageDice: "5d8",
        attackMod: 8,
        features: "3 Stress: Breath weapon (area). 2 Stress: Flight."
    },
                {
        name: "Drider",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Drow",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },        
        {
        name: "Dryad",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Duergar",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Dust Devil",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Dust Mephit",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Blinding - Select the target and Cause them to become Blinded. <i>Until the end of their next turn.</i> 1 Stress: Death Burst - When the creature is reduced to 0HP they explode and cause 1 Hit to all creatures within Melee range.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Efreeti",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
                {
        name: "Elemental (Air)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Elemental (Earth)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Elemental (Fire)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Elemental (Water)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Ettercap",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },        
        {
        name: "Ettin",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Faerie Dragon",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Spell-Caster - Can cast limited number of spells. 3 Stress: Magic Resistance - The creature has X Level Spell Resistance, taking half damage or Save with Advantage. 1 Stress: Breath Euphoria - Target becomes calm, relaxed and less inclinded to move. 1 Stress: Invisibility - The target cannot be seen. All Attacks against it are at Disadvantage all Attacks it makes are with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Fire Snake",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Aura Burning  - Any enemy creature in 10ft Range at the start of their turn also takes +5 per monster Tier damage. 1 Stress: Constrict - The target is Restrained unable to move, on this turn and the start of this creature's turn the target will take 1d6 damage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Flame Skull",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Flying Sword",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Formorian",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gas Spore",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Aura Poison  - Any enemy creature in 10ft Range at the start of their turn also takes +5 per monster Tier damage. 1 Stress: Suffocate - By removing the breathing air around the target they cannot breathe.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Gargoyle",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gelatinous Cube",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Ghast",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Ghost",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },       
        {
        name: "Ghoul",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Ghast",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Giant (Cloud)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Giant (Fire)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Giant (Frost)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Giant (Hill)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Giant (Stone)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Giant (Storm)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Giant Rat",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Diseased - Any target that is hit by the Giant rat must make a CON Save of gain the Diseased Condition. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Giant Spider",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Poisoned - Any target that is hit by the Giant rat must make a CON Save of gain the Poisoned Condition. 1 Stress: Web - The target must make a DEX Save or become entangled in the sticky webbing. Requiring a STR DC at the start of their turn to break free. 1 Stress: Spider Climb - The Creature can walk on Walls or Ceilings as if they are on flat ground. (<i>Terrain challenges may still apply.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gnoll",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "2 Stress: Aggresssive - Add +1 to all Damage dice rolled totals. (<i>Until the end of Combat.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Goblin",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble - Reduce incoming Hits by 1. Also cannot be Grappled or Restrained. 1 Stress: Quick Blade - If the creature misses its Attack, it can chose to make 1 Hit regardless.",
                        image: "monsters/goblin.png",
                description: "Small, cunning humanoids with green skin and sharp teeth. Goblins are cowardly but dangerous in groups, preferring ambush tactics and dirty fighting.",
                ecology: "Goblins live in tribal societies in caves, ruins, or makeshift settlements. They scavenge, raid, and steal to survive, often serving stronger creatures like hobgoblins or orcs.",
                combat: "Goblins rely on hit-and-run tactics, using their nimble escape ability to avoid retaliation. They prefer ranged attacks and overwhelming numbers over direct confrontation."
    },
            {
        name: "Golem (Clay)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Golem (Flesh)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Golem (Iron)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Golem (Stone)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Gorgon",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gray Ooze",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Corrode Metal - Each time the creature is hit, any item made of metal will begin to corrode and lose -1 to the Attack Roll (<i>Until it is repaired.</i>). Pseudopod - Make a ranged attack out to 10ft.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Grell",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Grick",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Griffon",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Multi-Attack - Attack X amount of time in a single action. 2 Stress: Aggresssive - Add +1 to all Damage dice rolled totals. (<i>Until the end of Combat.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Grimlock",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Hag (Green)",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },     
                {
        name: "Hag (Night)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Hag (Sea)",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Half-Ogre",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Harpy",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
    {
        name: "Hell Hound",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Breath Fire - Roll damage dice equal to the monster Tier and add the burning condition. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Helmed Horror",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
    {
        name: "Hippogriff",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Flyby - Moving quickly the creature can make an Attack within any reteliation and move out of Melee range. (<i>Move out 60ft plus.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Hobgoblin",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Armor - can reduce Hits by points equal to Modifier. 1 Stress: Advanced Tactics - If the Hobgoblin makes a successful Attack, add +1 Hit for all allies within 15ft.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Homunculus",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Poison Bite - the target must make a CON Save of gain the Posioned condition.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Hook Horror",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Echolocation - Immune to the Blinded condition.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Horned Devil",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Hydra",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Hyena",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Bone Crunch -  The target of a successful Attack wil roll Attack rolls with Disadvantage. (<i>Until they recieve healing, or a rest.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Incubus",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Imp",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Spell-Caster - Can cast limited number of spells. 1 Stress: Invisibility - The target cannot be seen. All Attacks against it are at Disadvantage all Attacks it makes are with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Intellect Devourer",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Intellect Devour - Cause 1d6 of Psychic Damage, the target will also lose that amount of Intelligence. (<i>Until a Lesser Restoration.</i>) 1 Stress: Body Thief - If a target's Intelligence is -3 the Devour can take control of the target.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Invisible Stalker",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Kobold",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Tricky - The Kobold has the ability to pull something out of nothing. <i>The GM may choose to appropriate action.</i> 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Kraken",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Kuo-Toa",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Slippery - Reduce incoming Hits by 1. Also cannot be Grappled or Restrained. 1 Stress: Sticky Shield - Make an Attack with their shield, the target is also Restrained, until a successful STR check. The Kuo-Toa can now make all Attacks on this target with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Lamia",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Lich",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Lizardfolk",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Hold Breath - The creature can indefinitely hold their breath. If they take 2 or more Hits they must take a breath. 1 Stress: Spiked Shield - Make an attack with the shield (2d6) add the Damage to the total, also push the target back 5ft on a failed STR Save.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Manticore",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Medusa",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Merfolk",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Amphibious - Can breath both air and in water. Has no restrictions on Attacks underwater. 1 Stress: Multi-Attack - Attack X amount of time in a single action.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Merrow",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Amphibious - Can breath both air and in water. Has no restrictions on Attacks underwater. 1 Stress: Multi-Attack - Attack X amount of time in a single action.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Mimic",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. Pseudopod - Make a ranged attack out to 10ft. 1 Stress: Adhere - Any target within Melee range must make a STR Save to resist the Grappled condition.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Mind FLayer",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Minotaur",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Mummy",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
        {
        name: "Myconid",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Empathy Spores - Target becomes calm, relaxed and in touch with the feelings of Myconid within 30ft.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                   {
        name: "Naga (Bone)",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Naga (Guardian)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Naga (Spirit)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Nalfeshnee",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Needle Blight",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 1 Stress: - Armor can reduce Hits by points equal to Modifier. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Nightmare",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Nothic",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Telepathic - (without Stress) Can send visual images to any creature seen within 30ft. Can cause 2d6 of Psychic Damage and pull deeper thoughts and memories from the target.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Ochre Jelly",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Pseudopod - Make a ranged attack out to 10ft. 1 Stress: Split - If the target has been attacked with a bladed weapon the creature can cause itself to split into 2 separate creatures. 1 Stress: Spider Climb - The Creature can walk on Walls or Ceilings as if they are on flat ground. (<i>Terrain challenges may still apply.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Ogre",
        tier: 2,
        hp: 6,
        stress: 4,
        evasion: 12,
        thresholdLow: 18,
        thresholdHigh: 25,
        damageDice: "1d10",
        attackMod: 5,
        features: "2 Stress: Smash - Hit all adjacent targets.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Oni",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Orc",
        tier: 1,
        hp: 5,
        stress: 3,
        evasion: 12,
        thresholdLow: 11,
        thresholdHigh: 20,
        damageDice: "1d12",
        attackMod: 5,
        features: "1 Stress: Brute - Add +1 Damage die to the total damage roll. 2 Stress: Aggresssive - Add +1 to all Damage dice rolled totals. (<i>Until the end of Combat.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Owlbear",
        tier: 2,
        hp: 6,
        stress: 4,
        evasion: 13,
        thresholdLow: 18,
        thresholdHigh: 30,
        damageDice: "1d8",
        attackMod: 5,
        features: "2 Stress: Rending claws - Extra 1d6 damage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Pegasus",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Noble Bond - If the creature chooses it will bond with another creature and form am emotional connection.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Phase Spider",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Pit Fiend",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
    {
        name: "Pixie",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Spell-Caster - Can cast limited number of spells.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Pesudodragon",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Sting - Cause the target to make a CON Save or fall asleep for 4 rounds, takes damage or roused by an ally. 3 Stress: Magic Resistance - The creature has X Level Spell Resistance, taking half damage or Save with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Purple Worm",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Quasit",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Fear - Force a WIS Save a creature that fails takes a Stress. 1 Stress: Invisibility - The target cannot be seen. All Attacks against it are at Disadvantage all Attacks it makes are with Advantage. 3 Stress: Magic Resistance - The creature has X Level Spell Resistance, taking half damage or Save with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Rakshasa",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Remorhaz",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Revenant",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                        {
        name: "Roc",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Roper",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Rug of Smothering",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 1 Stress: Grapple - Select a target and force them to roll a STR/DEX Save to resist. On a fail the target gains the Grappled condition.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Rust Monster",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
            {
        name: "Salamander",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Satyr",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Charge - If this creature has at least 5ft of movement they can ram an enemy forcing them back 10ft on a failed STR Save. 3 Stress: Magic Resistance - The creature has X Level Spell Resistance, taking half damage or Save with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Scarecrow",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 1 Stress: Fear - Force a WIS Save a creature that fails takes a Stress.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Shadow",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Shadow Demon",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },        
        {
        name: "Shambling Mound",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
        {
        name: "Skeleton",
        tier: 1,
        hp: 2,
        stress: 1,
        evasion: 11,
        thresholdLow: 5,
        thresholdHigh: 11,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: - Armor can reduce Hits by points equal to Modifier. 1 Stress: Evil Blade - Add +1 Damage die to the total damage roll.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Slaad",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Smoke Mephit",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Death Burst - When the creature is reduced to 0HP they explode and cause 1 Hit to all creatures within Melee range.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Spectator",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Specter",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Incorpral: Can move through objects without penalty, if the object is a living creature they must make a CON Save or take 2d6 Force Damage. 3 Stress: Life Drain - Remove 1HP from the target's total HP. (<i>Until after a Long Rest.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Spined Devil",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Devil's Sight - Can see beyond the material world, including anything hidden or invisible. Flyby - Moving quickly the creature can make an Attack within any reteliation and move out of Melee range. (<i>Move out 60ft plus.</i>) 3 Stress: Magic Resistance - The creature has X Level Spell Resistance, taking half damage or Save with Advantage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Sprite",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },    
        {
        name: "Stirge",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "3 Stress: Life Drain - Remove 1HP from the target's total HP. (<i>Until after a Long Rest.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Succubus",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Tarrasque",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Treant",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
                {
        name: "Troll",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Regenerate 1 HP. 2 Stress: Multi-attack.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Twig Blight",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                        {
        name: "Ultroloth",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Umber Hulk",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Unicorn",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Vampire",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Vine Blight",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "False Appearance - It impossible to tell this from any other item of its type. Gains Advantage on Surprise Attacks. 1 Stress: Grapple - Select a target and force them to roll a STR/DEX Save to resist. On a fail the target gains the Grappled condition. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Water Weird",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
            {
        name: "Wight",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Will-o-Wisp",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble - Reduce incoming Hits by 1. Also cannot be Grappled or Restrained. 3 Stress: Life Drain - Remove 1HP from the target's total HP. (<i>Until after a Long Rest.</i>)",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Winter Wolf",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Wolf",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "Keen Senses - The creature can Roll and Skill check for perception at Advantage. 2 Stress: Pack Tactics: Add +1 to attack rolls for each ally, combine damage roll total.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Worg",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Wraith",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Wyvern",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Xorn",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Yeti",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Yuan-Ti",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Zombie",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Relentless - If the creature drops to 0HP they can instead drop to 1HP. 1 Stress: Indomitable - Add +1 Damage die to the total damage roll.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
];

// Make the monsters available globally
window.defaultMonsters = defaultMonsters;
