// monsters.js - Monster Library
//NOTE: Stress: and GM Token: are keywords.
const defaultMonsters = [

    // You can easily add more monsters here:
        {
        name: "Ankheg",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Animated Armor",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Awakened Shrub",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Azer",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Balor",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
            {
        name: "Banshee",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Barbed Devil",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Barlgura",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
            {
        name: "Basilisk",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Behir",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Beholder",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Black Pudding",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Blink Dog",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Bone Devil",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Bugbear",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Bullwug",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Cambion",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Carrion Crawler",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Centaur",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Chain Devil",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
                {
        name: "Chimera",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },    
            {
        name: "Chuul",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },      
        {
        name: "Cloaker",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Cockatrice",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Couatl",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Crawling Claw",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Cyclops",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Death Dog",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Demi-Lich",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Death Knight",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Dire Wolf",
        tier: 2,
        hp: 4,
        stress: 3,
        evasion: 13,
        thresholdLow: 11,
        thresholdHigh: 20,
        damageDice: "1d6",
        attackMod: 5,
        features: "1 Stress: Pack Tactics - Advantage on next attack.",
                        image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Displacer Beast",
        tier: 1,
        hp: 4,
        stress: 3,
        evasion: 12,
        thresholdLow: 11,
        thresholdHigh: 20,
        damageDice: "1d6",
        attackMod: 5,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Djinni",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Doppleganger",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Dragon (Ancient)",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Dragon (Black)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Blue)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (Bronze)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Copper)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (Green)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Gold)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (Red)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Dragon (Silver)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Dragon Turtle",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Dragon (White)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Dragon (Young)",
        tier: 5,
        hp: 20,
        stress: 10,
        evasion: 17,
        thresholdLow: 29,
        thresholdHigh: 44,
        damageDice: "5d8",
        attackMod: 8,
        features: "3 Stress: Breath weapon (area). 2 Stress: Flight."
    },
                {
        name: "Drider",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Drow",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },        
        {
        name: "Dryad",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Duergar",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Dust Devil",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Dust Mephit",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Efreeti",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
                {
        name: "Elemental (Air)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Elemental (Earth)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Elemental (Fire)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Elemental (Water)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Ettercap",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },        
        {
        name: "Ettin",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Faerie Dragon",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Fire Snake",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Flame Skull",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Flying Sword",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Formorian",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gas Spore",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Gargoyle",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gelatinous Cube",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Ghast",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Ghost",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },       
        {
        name: "Ghoul",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Ghast",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Giant (Cloud)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Giant (Fire)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Giant (Frost)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Giant (Hill)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Giant (Stone)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Giant (Storm)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Giant Rat",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Giant Spider",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gnoll",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Goblin",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                        image: "monsters/goblin.png",
                description: "Small, cunning humanoids with green skin and sharp teeth. Goblins are cowardly but dangerous in groups, preferring ambush tactics and dirty fighting.",
                ecology: "Goblins live in tribal societies in caves, ruins, or makeshift settlements. They scavenge, raid, and steal to survive, often serving stronger creatures like hobgoblins or orcs.",
                combat: "Goblins rely on hit-and-run tactics, using their nimble escape ability to avoid retaliation. They prefer ranged attacks and overwhelming numbers over direct confrontation."
    },
            {
        name: "Golem (Clay)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Golem (Flesh)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Golem (Iron)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Golem (Stone)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Gorgon",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Gray Ooze",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Grell",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Grick",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Griffon",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Grimlock",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Hag (Green)",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },     
                {
        name: "Hag (Night)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Hag (Sea)",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Half-Ogre",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Harpy",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
    {
        name: "Hell Hound",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Helmed Horror",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
    {
        name: "Hippogriff",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Hobgoblin",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Homunculus",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Hook Horror",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Horned Devil",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Hydra",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Hyena",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Incubus",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Imp",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Intellect Devourer",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Invisible Stalker",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Kobold",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Kraken",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Kuo-Toa",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Lamia",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Lich",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Lizardfolk",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Manticore",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Medusa",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Merfolk",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Merrow",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Mimic",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Mind FLayer",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Minotaur",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Mummy",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
        {
        name: "Myconid",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                   {
        name: "Naga (Bone)",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Naga (Guardian)",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Naga (Spirit)",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Nalfeshnee",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Needle Blight",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Nightmare",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Nothic",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Ochre Jelly",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Ogre",
        tier: 2,
        hp: 6,
        stress: 4,
        evasion: 12,
        thresholdLow: 18,
        thresholdHigh: 25,
        damageDice: "1d10",
        attackMod: 5,
        features: "2 Stress: Smash - Hit all adjacent targets.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Oni",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Orc",
        tier: 1,
        hp: 5,
        stress: 3,
        evasion: 12,
        thresholdLow: 11,
        thresholdHigh: 20,
        damageDice: "1d12",
        attackMod: 5,
        features: "1 Stress: Brutal Strike - +1d4 damage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Owlbear",
        tier: 2,
        hp: 6,
        stress: 4,
        evasion: 13,
        thresholdLow: 18,
        thresholdHigh: 30,
        damageDice: "1d8",
        attackMod: 5,
        features: "2 Stress: Rending claws - Extra 1d6 damage.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Pegasus",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Phase Spider",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Pit Fiend",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
    {
        name: "Pixie",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
    {
        name: "Pesudodragon",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                    {
        name: "Purple Worm",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Quasit",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Rakshasa",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Remorhaz",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Revenant",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                        {
        name: "Roc",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Roper",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Rug of Smothering",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Rust Monster",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
            {
        name: "Salamander",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Satyr",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Scarecrow",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Shadow",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Shadow Demon",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },        
        {
        name: "Shambling Mound",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },  
        {
        name: "Skeleton",
        tier: 1,
        hp: 2,
        stress: 1,
        evasion: 11,
        thresholdLow: 5,
        thresholdHigh: 11,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Bone shield - Reduce next attack by 2.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Slaad",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Smoke Mephit",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Spectator",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Specter",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Spined Devil",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Sprite",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },    
        {
        name: "Stirge",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Succubus",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Tarrasque",
        tier: 5,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Treant",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
                {
        name: "Troll",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Regenerate 1 HP. 2 Stress: Multi-attack.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Twig Blight",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                        {
        name: "Ultroloth",
        tier: 4,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Umber Hulk",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Unicorn",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
                {
        name: "Vampire",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
        {
        name: "Vine Blight",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Water Weird",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    }, 
            {
        name: "Wight",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Will-o-Wisp",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Winter Wolf",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Wolf",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Worg",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Wraith",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Wyvern",
        tier: 3,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
            {
        name: "Xorn",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Yeti",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },   
        {
        name: "Yuan-Ti",
        tier: 2,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
        {
        name: "Zombie",
        tier: 1,
        hp: 2,
        stress: 2,
        evasion: 12,
        thresholdLow: 6,
        thresholdHigh: 12,
        damageDice: "1d6",
        attackMod: 2,
        features: "1 Stress: Nimble Escape - Reduce hits by 1.",
                                image: "monsters/",
                description: "",
                ecology: "",
                combat: ""
    },
];

// Make the monsters available globally
window.defaultMonsters = defaultMonsters;
